### ISSUE TITLE
Use of ALICE

### ISSUE THREAD

**Issue by damercer** [StefanMack/M1K#1]
Please do not use ALICE in the name(s) of any software you write. The name ALICE as used to refer to the Active Learning Interface for Circuits and Electronics software for use with the ADALM1000 (or any other Analog Devices products) is copyrighted by Analog Devices Inc. Feel free to use sections or fragments of the code for your educational purposes but please refrain from using ALICE in the name of any M1k related software you publish to not confuse potential users who may seek support from ADI. 

Thanks you and regards.

Doug Mercer (ADI)

**Comment by StefanMack** [comment]
The software was renamed today as "smuc". "smuc" stands for Source Measurement Unit Control.
